### PR TITLE
#294 Update jackson dependencies to 2.9.1

### PR DESCRIPTION
**Pull request by ccannell67**

### CODE REVIEW

**Comment by ccannell67** [comment]
The failed Travis tests seem to be with Travis, not the actual commits/pr. I have been testing against just the master and get intermittent/inconsistent passes and fails for the different versions.

Is this a known issue?

**Comment by jordansissel** [comment]
> to fix vulnerability.

We are aware of this Jackson vulnerability. The issue in question is a vulnerability in the Jackson polymorphic deserialization feature. We reviewed the issue and determined we do not use this codepath in Logstash nor in Logstash beats input. It is not possible for an attacker to trigger the flaws in question. This issue does not affect Elasticsearch.

This said, I'm fine with upgrading the version of Jackson, but the reason for the upgrade claims vulnerability to something which Logstash does not appear vulnerable. Can you update the changelog to remove the CVE mention as well as the commit message to remove the vulnerability claim?

If you have verification of the claim that Logstash beats input plugin is vulnerable, please contact security@elastic.co and do not use public channels such as GitHub.

**Comment by ccannell67** [comment]
OK, updated.

**Comment by alex-dr** [comment]
This plugin is packaged in logstash (at least, it is in CentOS) and while I understand that this library is not affected by this class of vulnerabilities I appreciate your willingness to upgrade your dependent libraries. This helps us operate in environments where security controls, we might say, are stricter than good sense.

To that end, since something is failing in the CI build anyway, I was wondering if @ccannell67 would be willing to change the bump all the way to 2.9.4, which resolves a few more CVE's against the upstream package.

**Comment by ccannell67** [comment]
Actually the core is using 2.9.1, https://github.com/elastic/logstash/blob/b3366d7ed6a71f0bceef69536c764cbc0eb2020a/versions.yml

That is why I used that version. For consistency.

**Comment by alex-dr** [comment]
It's not a trivial patchset; 139 commits, nor am I set up to run tests.

https://github.com/FasterXML/jackson-databind/blob/master/release-notes/VERSION-2.x#L16-L107

I vote we also PR core. I've also got a PR to bump jrjackson since it also gets bundled in: https://github.com/guyboertje/jrjackson/pull/66

**Comment by alex-dr** [comment]
Glad to hear someone else is in the same boat ;)

**Comment by ccannell67** [comment]
May as well. After actually slowing down and looking at the versions/branches, this won't help me immediately anyway, as I am on ES/Logstash 5.6 and it uses logstash-input-beats version 3.x.
https://github.com/elastic/logstash/commit/eb110a2865b48b9a50a20191227d4f17302e48dc

**Comment by jakelandis** [comment]
@ccannell67 - Thanks for the contribution! 

Let's get to Jackson `2.9.4` in two separate steps. Can you do the following and I will merge this PR:
* remove " to fix vulnerability." from the commit log, since there is no actual vulnerability given the scope of use, and git history is forever. 
* roll back this PR back to only bump to `2.9.1` 
* submit a new PR to bump to `2.9.4` 

I will then merge this PR and https://github.com/logstash-plugins/logstash-input-beats/pull/297 and push a release master and 3.x release with the `2.9.1` version. 

I would like to keep the Jackson version in sync with core, and core is dependent on https://github.com/guyboertje/jrjackson/pull/66.  Once that gets merged, we can bump to `2.9.4` across the stack. Whew...

**Comment by ccannell67** [comment]
@jakelandis I have the commits and PR sorted. Thanks!

**Comment by jakelandis** [comment]
Changes look good , thanks again @ccannell67 .  merging...

**Comment by jakelandis** [comment]
This has been released.  To upgrade:
`bin/logstash-plugin update logstash-input-beats`

**Comment by alex-dr** [comment]
https://github.com/guyboertje/jrjackson/pull/67

jrjackson is bumped to 2.9.4, so I guess it's time for 

> submit a new PR to bump to 2.9.4

Thanks for the quick response everyone!

**Comment by jakelandis** [comment]
@alex-dr @ccannell67 - beats input Jackson dependency has been bumpted to `2.9.4` in 
beats input `3.1.29` and `5.0.10` , this should be the default versions in the next patch release of Logstash 5.x and 6.x.

**Pull request closed without merging**
