### PR TITLE
Add cipher for receiving data from logstash-output-lumberjack

### PR DESCRIPTION
**Pull request by cwurm**
When connecting two Logstash instances using `logstash-output-lumberjack` and `logstash-input-beats` and turning on SSL, the connection fails with a `#<OpenSSL::SSL::SSLError: Received fatal alert: handshake_failure>`.

While hard/impossible to see from the logs, this seems to be due to incompatible cipher suites. There's a number of suites that both plugins support, but only one suite overlaps at the moment (`TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256`), and it doesn't seem to work with that one - at least on my machine.

*Cipher suites supported by `logstash-output-lumberjack` (observed when running with `-Djavax.net.debug=all`):*
```
Cipher Suites: [TLS_DHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_DSS_WITH_AES_256_CBC_SHA, 
TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_DSS_WITH_AES_128_CBC_SHA, 
SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA, SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA, 
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, 
TLS_RSA_WITH_AES_256_CBC_SHA, TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA, 
TLS_ECDH_RSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, 
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256, 
TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, 
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA, 
TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDH_RSA_WITH_AES_128_CBC_SHA]
```

*Cipher suites supported by `logstash-input-beats` by default (https://www.elastic.co/guide/en/logstash/current/plugins-inputs-beats.html#plugins-inputs-beats-cipher_suites):*
```
[TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, 
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, 
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, 
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, 
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384, 
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, 
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256]
```

I copy pasted all suites from `logstash-output-lumberjack` as a value for the `cipher_suites` parameter of `logstash-input-beats`. These are the ones that worked (compatibility levels from https://wiki.mozilla.org/Security/Server_Side_TLS):
```
TLS_DHE_RSA_WITH_AES_256_CBC_SHA (Intermediate)
TLS_DHE_RSA_WITH_AES_128_CBC_SHA (Intermediate)
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (Intermediate)
TLS_RSA_WITH_AES_256_CBC_SHA (Intermediate)
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (Modern)
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (Intermediate)
TLS_RSA_WITH_AES_128_CBC_SHA (Intermediate)
```

Since `TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256` is the only modern one on that list this is the one that I propose adding to the default.

**Working configuration**
`logstash-sender.conf`
```
input {
  generator {
    lines => [
      "line 1",
      "line 2",
      "line 3"
    ]
    count => 1
  }
}

filter {
}

output {
  lumberjack {
    port => 16000
    hosts => ["localhost"]
    ssl_certificate => "/path/to/cert.pem"
  }
}
```

`logstash-receiver.conf`
```
input {
  beats {
    port => 16000
    ssl => true
    ssl_certificate => "/path/to/cert.pem"
    ssl_key => "/path/to/key.pkcs8.pem"
    cipher_suites => [TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256]
  }
}

filter {
}

output {
  stdout {
    codec => rubydebug
  }
}
```

**Logstash**
Logstash 5.4.0

**OS**
macOS Sierra 10.2.5

**Java**
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

### CODE REVIEW

**Comment by jakelandis** [comment]
@cwurm - Thanks for the contribution!

Looks good, I will merge it in for the next release.  Do you need this back patched to be compatible with Logstash 5.x ?

**Comment by cwurm** [comment]
@jakelandis Would be sweet to get it into 5.x. I thought plugins are versioned independently and LS will include the newest version automatically?

**Comment by jakelandis** [comment]
@cwurm - there is a non passive change in master, so we are maintaining two steams of code for this plugin. 

I will get it merged and should make the 6.0.0 and 5.6 releases.

**Comment by jakelandis** [comment]
Will merge on 3.x on separate PR.

**Comment by cwurm** [comment]
Thanks @jakelandis.

**Comment by jakelandis** [comment]
Released in:

[4.0.5](https://rubygems.org/gems/logstash-input-beats/versions/4.0.5-java) (6.x branch)
and
[3.1.22](https://rubygems.org/gems/logstash-input-beats/versions/3.1.22-java) (5.x branch)

**Pull request closed without merging**
