### PR TITLE
relax concurrent-ruby dependency to ~> 0.9.2

### PR DESCRIPTION
**Pull request by ph**

### CODE REVIEW

**Comment by ph** [comment]
@suyograo See the parent issue https://github.com/elastic/logstash/issues/4235

**Comment by ph** [comment]
I will check why the test is failling too. bummer.

**Comment by colinsurprenant** [comment]
looking at the logs its using logstash-core 2.0.0 and not picking the latest 2.1.0.snapshot2 logstash-core which hard wires concurrent-ruby to 0.9.2 ? why!?

**Comment by colinsurprenant** [comment]
so, the change here LGTM but we need to understand why the build is failing...

**Comment by jordansissel** [comment]
Change LGTM also

**Comment by ph** [comment]
@colinsurprenant @jordansissel It fails because it uses `Using logstash-core 2.0.0` in the bundle install.

**Comment by ph** [comment]
It install logstash-core 2.0.1 and not 2.1.0.snapshot2,

Bundler will prefer non prerelease gem unless you specify them.
```
~/e/l/logstash-input-beats git:fix/concurrent-ruby ❯❯❯ rm *.lock                                                                                                                                                                                                                                                                                                      ⏎ ◼
~/e/l/logstash-input-beats git:fix/concurrent-ruby ❯❯❯ bundle install
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies.......
Using rake 10.4.2
Using cabin 0.7.2
Using clamp 0.6.5
Using coderay 1.1.0
Installing concurrent-ruby 0.9.2
Using diff-lcs 1.2.5
Using ffi 1.9.10
Using filesize 0.0.4
Using flores 0.0.6
Using gem_publisher 1.5.0
Using gems 0.8.3
Using i18n 0.6.9
Using insist 1.0.0
Using jls-grok 0.11.2
Using jrjackson 0.3.7
Using jruby-openssl 0.9.12
Using kramdown 1.9.0
Using minitar 0.5.4
Using method_source 0.8.2
Using slop 3.6.0
Using spoon 0.0.4
Using pry 0.10.3
Using stud 0.0.22
Using thread_safe 0.3.5
Using polyglot 0.3.5
Using treetop 1.4.15
Installing logstash-core 2.0.1
Using logstash-patterns-core 2.0.2
Using logstash-codec-multiline 2.0.3
Using logstash-codec-plain 2.0.2
Using rspec-support 3.1.2
Using rspec-core 3.1.7
Using rspec-expectations 3.1.2
Using rspec-mocks 3.1.3
Using rspec 3.1.0
Installing rspec-wait 0.0.8
Using logstash-devutils 0.0.18
Using logstash-input-beats 2.0.0 from source at .
Using bundler 1.10.6
Bundle complete! 7 Gemfile dependencies, 39 gems now installed.
Bundled gems are installed into ./vendor.
```

**Comment by colinsurprenant** [comment]
ok, makes sense. so what will be the impact on the current 2.x users that will update plugins?

**Comment by ph** [comment]
I believe the jenkins' job workspace for PR testing isn't cleared between run and it use the existing `.lock` of a previous PR.

if you look at the end or the beginning of the log I don't see a delete workspace.

**Comment by ph** [comment]
@colinsurprenant this is a good question, I  have found out the problem is worse than i though :(

I looked at the 2.0 release, the lock is 

```
concurrent-ruby (0.9.1-java)
```

`logstash-core`'s gemspec is 

```
`gem.add_runtime_dependency "concurrent-ruby", "~> 0.9.1"`
```

do:

```
bin/plugin update logstash-codec-multline
```

lock file constains 0.9.2
```
concurrent-ruby (0.9.2-java)
```

Your environment is now :hankey:  :(

**Comment by colinsurprenant** [comment]
@ph ok for Jenkins, this is something we should look into, to clean the env, did @purbon work on this? 

For the versions, I don't understand why updating multiline updates concurrent-ruby, but regardless ... why is having concurrent-ruby upgraded to 0.9.2 :hankey: ?

**Comment by ph** [comment]
@colinsurprenant Because of a patch we did. https://github.com/elastic/logstash/blob/v2.0.0/lib/logstash/patches/silence_concurrent_ruby_warning.rb#L20-L53 (This is v2.0.0)

**Comment by colinsurprenant** [comment]
ah yes, ok, right, that patch makes it craps for 2.0 release. in 2.1 it will be ok.

**Comment by ph** [comment]
@colinsurprenant as   discussed with @suyograo we will release 2.0.1/1.5.6 when the jruby windows fix land.

**Comment by colinsurprenant** [comment]
:+1:

**Pull request closed without merging**
