### PR TITLE
Documentation: Add remote_ip to example configuration

### LINKED ISSUE #249: Documentation: Remote IP
Add documentation for the Remote IP address from on Issue #180.

### PR DESCRIPTION
**Pull request by jakelandis**
Fixes #249

Thanks for contributing to Logstash! If you haven't already signed our CLA, here's a handy link: https://www.elastic.co/contributor-agreement/

### CODE REVIEW

**Comment by jakelandis** [comment]
@acchen97 - Can you review the documentation change ?

I didn't see anywhere that we explicitly document the @metadata fields, so I just added it to the example. 

How we document here should be similar to the TCP input which also has this value (as 5.0.0) https://github.com/logstash-plugins/logstash-input-tcp/issues/81

**Comment by acchen97** [comment]
@jakelandis thanks for this. It might make sense to have a brief annotation for this. Thoughts around the below?

> Incoming events from Beats include metadata information around the IP address of the host the Beat collected the event from. For example, this field can be accessed and enriched in the core event:
> 
> ```
> filter {
>   mutate {
>     add_field => { "remote_ip" => "%{[@metadata][ip_address]}" }
>   }
> }
> ```

**Comment by acchen97** [comment]
@jakelandis FYI, nice example from @suyograo on the Kafka plugin: https://github.com/logstash-plugins/logstash-input-kafka/commit/cac9d596113e3621e64dfa55dcc704fd9af561f5

**Comment by jsvd** [comment]
this looks like a quick win for improving users' experience and understanding, poking @jakelandis so this doesn't get stale

**Comment by Toffs-Rocky** [comment]
When I add this config, most events can get ip address, but some events show this value “%{[@metadata][ip_address]}”. Anyone encountered this problem?

**Comment by jakelandis** [comment]
closing this PR as stale

**Pull request closed without merging**
