### PR TITLE
Include Remote IP address in the Event medata

### LINKED ISSUE #180: Include Remote IP address in the Event medata
Currently, every event generated by the beats input contain the `beat.hostname` this information is copied from the original metadata sent by the client.  In some case it might be good to know the ip adress of the client to do better filtering.

I suggest we use the information on the connected client to add a new field named `beat.ip_address` that will hold the IP address

### PR DESCRIPTION
**Pull request by jakelandis**
Adds ip_address to the @metadata field. The ip is the remote host address as seen by Netty.

Fixes #180

Thanks for contributing to Logstash! If you haven't already signed our CLA, here's a handy link: https://www.elastic.co/contributor-agreement/

### CODE REVIEW

**Comment by jakelandis** [comment]
Close and Reopen to kick off Travis again. 

(unrelated/random) Test failure issue : https://github.com/logstash-plugins/logstash-input-beats/issues/219

**Comment by jakelandis** [comment]
Travis failed again.... different reason.

See: https://github.com/logstash-plugins/logstash-input-beats/issues/219

Close/Reopen again.

**Comment by jakelandis** [comment]
Grr... can't get a clean build. Failures are un-related to the code, but would prefer to wait for green before merging. 

See #222

**Comment by acchen97** [comment]
@jakelandis thanks for taking care of this one. Should we update the plugin documentation to show that this metadata is now available? I suspect many users will find this feature useful.

**Comment by jakelandis** [comment]
@acchen97 - thanks for the reminder. I have logged https://github.com/logstash-plugins/logstash-input-beats/issues/249 to address the documentation.

**Pull request closed without merging**
